name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        versions:
          - {py_version: "3.9", tox_env: "py39"}
          - {py_version: "3.10", tox_env: "py310"}
          - {py_version: "3.11", tox_env: "py311"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.versions.py_version }}
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.versions.tox_env }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e cov
      - name: Install pytest cov
        run: pip install pytest-cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
